version: "3.0"

services:
  postgres:
    image: "postgres:15-bullseye"
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_DB: "cyb"
      POSTGRES_PASSWORD: "cyb"
      POSTGRES_USER: "cyb"
    ports:
      - "5432:5432"
