version: "3.0"

services:
  postgres:
    image: "postgres:14.5-bullseye"
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_DB: "wiki"
      POSTGRES_PASSWORD: "wikijsrocks"
      POSTGRES_USER: "wikijs"
    ports:
      - "5432:5432"
