[package]
name = "api"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "api"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
core = { path = "../core" }
database = { path = "../database" }
entity = { path = "../database/entity" }
migration = { path = "../database/migration" }
salvo = { version = "0.41.0", features = ["compression", "logging", "serve-static"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.19", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"

[dev-dependencies]
