[package]
name = "api"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "api"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
modules = { path = "../modules" }
database = { path = "../database" }
entity = { path = "../database/entity" }
migration = { path = "../database/migration" }
salvo = { version = "0.49.1", features = ["caching-headers", "compression", "cors", "logging", "oapi", "serve-static"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"

[dev-dependencies]
