name: Security Audit

on:
  # Schedule daily updates.
  schedule: [ { cron: "0 0 * * *" } ]
  # (optional) Run workflow manually.
  workflow_dispatch:
  # (optional) Run workflow when pushing on master.
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: rust-audit-check
        uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
